### ISSUE TITLE
Django versions

### ISSUE THREAD

**Issue by jnayak1** [zestedesavoir/django-cors-middleware#34]
Django 1.9 and 1.10 didn't work for me with this package. I switched to 1.8 and everything works great. 
Using:
- python 2.7
- django-rest-framework
- rest-framework-json-api

**Comment by bittner** [comment]
Looks like you should switch over to [django-cors-headers](https://github.com/ottoyiu/django-cors-headers#django-cors-headers). All recent Django versions are now supported.

**Comment by artragis** [comment]
We have to rework it. We forked django-cors-headers because it we no longer maintained but its development restarted. 

I will try to find out why djang0 1.9 and 1.10 do not work because in zestedesavoir-zds-site we do use django 1.10 successfuly. 

Do you have more info?

**Comment by bittner** [comment]
@artragis I noticed that this issue is almost 16 months old. Maybe it's no longer valid.

We should add Django 2.0 to the build matrix, also update the README, and verify that the tests make sense when the actually all do pass.

In the end, though, an incomplete bug report doesn't help a lot, that is correct. Especially when the tests pass ([what they do](https://travis-ci.org/zestedesavoir/django-cors-middleware)).

**Comment by artragis** [comment]
I'll try to take the project back
